### ISSUE TITLE
Add price checker

### ISSUE THREAD

**Issue by allegrocy** [allegrocy/ascalongw-discord-bot#4]
**Basic function**
- Check prices using Jon's kamadan-trade-chat

**Added functionality**
- Use reactions to scroll through trade chat
- More information on average, minimum and maximum price?

**Example of old price checker**
![image](https://user-images.githubusercontent.com/58875492/96399887-0949d400-1202-11eb-85c9-db4d95a24d7b.png)

**Comment by 3vcloud** [comment]
Done, and added relative times. Note that the new trade site doesn't use pages, so the number of results has been upped to 10. User can just click the URL to view more
